/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import test from "./about.gltf"
console.log('test', test)
const AboutScene = forwardRef((props, ref) => {
  const { nodes } = useGLTF(test);
  return (
    <group ref={ref} {...props} dispose={null}>
      <group position={[-2.19, -0.93, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube1.geometry}
          material={nodes.cube1.material}
          position={[-0.47, 0, -0.16]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tube4001.geometry}
            material={nodes.Tube4001.material}
            position={[0.03, 0.09, -0.04]}
            rotation={[0.39, 0.61, 1.87]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tube4002.geometry}
            material={nodes.Tube4002.material}
            position={[0.12, 0.15, -0.09]}
            rotation={[0.39, 0.61, 1.87]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tube4003.geometry}
            material={nodes.Tube4003.material}
            position={[0.22, 0.21, -0.13]}
            rotation={[0.39, 0.61, 1.87]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tube4004.geometry}
            material={nodes.Tube4004.material}
            position={[0.32, 0.27, -0.18]}
            rotation={[0.39, 0.61, 1.87]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tube4005.geometry}
            material={nodes.Tube4005.material}
            position={[0.42, 0.33, -0.23]}
            rotation={[0.39, 0.61, 1.87]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tube4006.geometry}
            material={nodes.Tube4006.material}
            position={[0.51, 0.39, -0.28]}
            rotation={[0.39, 0.61, 1.87]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tube4007.geometry}
            material={nodes.Tube4007.material}
            position={[0.61, 0.45, -0.33]}
            rotation={[0.39, 0.61, 1.87]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tube4008.geometry}
            material={nodes.Tube4008.material}
            position={[-0.07, 0.03, 0.01]}
            rotation={[0.39, 0.61, -1.27]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tube4009.geometry}
            material={nodes.Tube4009.material}
            position={[0.03, 0.09, -0.04]}
            rotation={[0.39, 0.61, -1.27]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tube4010.geometry}
            material={nodes.Tube4010.material}
            position={[0.12, 0.15, -0.09]}
            rotation={[0.39, 0.61, -1.27]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tube4011.geometry}
            material={nodes.Tube4011.material}
            position={[0.22, 0.21, -0.13]}
            rotation={[0.39, 0.61, -1.27]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tube4012.geometry}
            material={nodes.Tube4012.material}
            position={[0.32, 0.27, -0.18]}
            rotation={[0.39, 0.61, -1.27]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tube4013.geometry}
            material={nodes.Tube4013.material}
            position={[0.42, 0.33, -0.23]}
            rotation={[0.39, 0.61, -1.27]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tube4014.geometry}
            material={nodes.Tube4014.material}
            position={[0.51, 0.39, -0.28]}
            rotation={[0.39, 0.61, -1.27]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tube4015.geometry}
            material={nodes.Tube4015.material}
            position={[0.61, 0.45, -0.33]}
            rotation={[0.39, 0.61, -1.27]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tube4020.geometry}
            material={nodes.Tube4020.material}
            position={[-0.07, 0.03, 0.01]}
            rotation={[0.39, 0.61, 1.87]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube1001.geometry}
          material={nodes.cube1001.material}
          position={[0.32, -0.1, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tube4016.geometry}
            material={nodes.Tube4016.material}
            position={[-0.06, -0.02, -0.02]}
            rotation={[-2.36, 0.71, 2.14]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tube4017.geometry}
            material={nodes.Tube4017.material}
            position={[0.02, -0.12, -0.02]}
            rotation={[-2.36, 0.71, 2.14]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tube4018.geometry}
            material={nodes.Tube4018.material}
            position={[0.1, -0.21, -0.02]}
            rotation={[-2.36, 0.71, 2.14]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tube4019.geometry}
            material={nodes.Tube4019.material}
            position={[0.18, -0.31, -0.01]}
            rotation={[-2.36, 0.71, 2.14]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tube4024.geometry}
            material={nodes.Tube4024.material}
            position={[-0.06, -0.02, -0.02]}
            rotation={[-2.36, 0.71, -1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tube4025.geometry}
            material={nodes.Tube4025.material}
            position={[0.02, -0.12, -0.02]}
            rotation={[-2.36, 0.71, -1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tube4026.geometry}
            material={nodes.Tube4026.material}
            position={[0.1, -0.21, -0.02]}
            rotation={[-2.36, 0.71, -1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tube4027.geometry}
            material={nodes.Tube4027.material}
            position={[0.18, -0.31, -0.01]}
            rotation={[-2.36, 0.71, -1]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plastic_Bi.geometry}
          material={nodes.Plastic_Bi.material}
          position={[-0.69, -0.26, 0.17]}
          rotation={[-0.84, -0.09, 1.22]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wire.geometry}
            material={nodes.Wire.material}
            scale={[0.79, 0.79, 0.79]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plastic_Bi002.geometry}
          material={nodes.Plastic_Bi002.material}
          position={[0.51, 0.68, 0.17]}
          rotation={[0.17, 0.83, -0.65]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wire002.geometry}
            material={nodes.Wire002.material}
            scale={[0.79, 0.79, 0.79]}
          />
        </mesh>
      </group>
      <group position={[2.05, 0.9, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.shoe.geometry}
          material={nodes.shoe.material}
          position={[-0.38, 0.37, -0.21]}
          rotation={[-0.21, 0.65, -2.8]}
          scale={5.75}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.shoelace.geometry}
            material={nodes.shoelace.material}
            position={[-0.01, 0.03, 0.01]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.shoe001.geometry}
          material={nodes.shoe001.material}
          position={[0.4, -0.07, -0.08]}
          rotation={[-2.75, 0.93, -0.47]}
          scale={[-5.75, -5.75, -5.75]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.shoelace001.geometry}
            material={nodes.shoelace001.material}
            position={[-0.01, 0.03, 0.01]}
          />
        </mesh>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Skullcandy_Crusher.geometry}
        material={nodes.Skullcandy_Crusher.material}
        position={[-0.22, -1.39, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.node_id74.geometry}
        material={nodes.node_id74.material}
        position={[-2.36, 1.12, -0.36]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes["appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes"]
            .geometry
        }
        material={
          nodes["appstorageapprawf3479520-7389-11ec-873d-5fe6ac4d76fes"]
            .material
        }
        position={[2.3, -1.01, 0]}
      />
    </group>
  );
});

useGLTF.preload(test);
export default AboutScene;
